export const LOCAL_RECORDING_ON = Symbol('LOCAL_RECORDING_ON');
export const LOCAL_RECORDING_OFF = Symbol('LOCAL_RECORDING_OFF');
export const LOCAL_RECORDING_TOGGLE_DIALOG = Symbol('LOCAL_RECORDING_TOGGLE_DIALOG');
export const CLOCK_TICK = Symbol('CLOCK_TICK');
