export const LOCAL_RECORDING_ON = Symbol('LOCAL_RECORDING_ON');
export const LOCAL_RECORDING_OFF = Symbol('LOCAL_RECORDING_OFF');
export const LOCAL_RECORDING_TOGGLE_DIALOG
    = Symbol('LOCAL_RECORDING_TOGGLE_DIALOG');
export const LOCAL_RECORDING_STATS_UPDATE
    = Symbol('LOCAL_RECORDING_STATS_UPDATE');
export const CLOCK_TICK = Symbol('CLOCK_TICK');
